//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trebuchet.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trebuchet.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Exists.
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already used.
        /// </summary>
        internal static string AlreadyExistsText {
            get {
                return ResourceManager.GetString("AlreadyExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion.
        /// </summary>
        internal static string Deletion {
            get {
                return ResourceManager.GetString("Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete the selected profile {0} ?.
        /// </summary>
        internal static string DeletionText {
            get {
                return ResourceManager.GetString("DeletionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exists.
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game could not be found in this Directory.
        /// </summary>
        internal static string GameDirectoryInvalidError {
            get {
                return ResourceManager.GetString("GameDirectoryInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Folder Reset.
        /// </summary>
        internal static string GameFolderReset {
            get {
                return ResourceManager.GetString("GameFolderReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your game directory contain saved data from your previous use of the game. Game Directory has been reset, please set it up again..
        /// </summary>
        internal static string GameFolderResetText {
            get {
                return ResourceManager.GetString("GameFolderResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameSaves.
        /// </summary>
        internal static string GameSaves {
            get {
                return ResourceManager.GetString("GameSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Data.
        /// </summary>
        internal static string HandleOriginalSavedDirectory {
            get {
                return ResourceManager.GetString("HandleOriginalSavedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your game directory contain saved data from your previous use of the game. In order to use the features of the launcher, the folder will be renamed and its content copied into a new profile to use with the launcher. All your data will still be under the folder Saved_Original.\nDo you wish to continue ?.
        /// </summary>
        internal static string HandleOriginalSavedDirectoryText {
            get {
                return ResourceManager.GetString("HandleOriginalSavedDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install path cannot be in the game Saved folder.
        /// </summary>
        internal static string InstallPathInGameError {
            get {
                return ResourceManager.GetString("InstallPathInGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is invalid.
        /// </summary>
        internal static string InvalidDirectory {
            get {
                return ResourceManager.GetString("InvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Json.
        /// </summary>
        internal static string InvalidJson {
            get {
                return ResourceManager.GetString("InvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded json could not be parsed..
        /// </summary>
        internal static string InvalidJsonText {
            get {
                return ResourceManager.GetString("InvalidJsonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The steam URL seems to be missing its ID to be valid..
        /// </summary>
        internal static string InvalidURLText {
            get {
                return ResourceManager.GetString("InvalidURLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing a process will trigger an abrupt ending of the program and can lead to Data loss and/or data corruption. Do you wish to continue ?.
        /// </summary>
        internal static string KillText {
            get {
                return ResourceManager.GetString("KillText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        internal static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Workshop (Live).
        /// </summary>
        internal static string LiveMod {
            get {
                return ResourceManager.GetString("LiveMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local File.
        /// </summary>
        internal static string LocalMod {
            get {
                return ResourceManager.GetString("LocalMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Filter.
        /// </summary>
        internal static string LogFilter {
            get {
                return ResourceManager.GetString("LogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modlist Name.
        /// </summary>
        internal static string ModlistName {
            get {
                return ResourceManager.GetString("ModlistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        internal static string Mods {
            get {
                return ResourceManager.GetString("Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name.
        /// </summary>
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Consoles.
        /// </summary>
        internal static string ServerConsoles {
            get {
                return ResourceManager.GetString("ServerConsoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server failed to start.
        /// </summary>
        internal static string ServerFailedStart {
            get {
                return ResourceManager.GetString("ServerFailedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server failed to start properly. See the logs for more information..
        /// </summary>
        internal static string ServerFailedStartText {
            get {
                return ResourceManager.GetString("ServerFailedStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some server instances are not yet installed..
        /// </summary>
        internal static string ServerNotInstalled {
            get {
                return ResourceManager.GetString("ServerNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Saves.
        /// </summary>
        internal static string ServerSaves {
            get {
                return ResourceManager.GetString("ServerSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Workshop (TestLive).
        /// </summary>
        internal static string TestLiveMod {
            get {
                return ResourceManager.GetString("TestLiveMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebuchet is busy..
        /// </summary>
        internal static string TrebuchetBusy {
            get {
                return ResourceManager.GetString("TrebuchetBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string UACDialog {
            get {
                return ResourceManager.GetString("UACDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following folder is protected by administrator rights, Trebuchet need access to manage your game and data. Restart Trebuchet in Admin mode ?\n{0}.
        /// </summary>
        internal static string UACDialogText {
            get {
                return ResourceManager.GetString("UACDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpToDate.
        /// </summary>
        internal static string Up_to_Date {
            get {
                return ResourceManager.GetString("Up to Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating mods.
        /// </summary>
        internal static string UpdateModsLabel {
            get {
                return ResourceManager.GetString("UpdateModsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating servers.
        /// </summary>
        internal static string UpdateServersLabel {
            get {
                return ResourceManager.GetString("UpdateServersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying mod files.
        /// </summary>
        internal static string VerifyModsLabel {
            get {
                return ResourceManager.GetString("VerifyModsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying server files.
        /// </summary>
        internal static string VerifyServersLabel {
            get {
                return ResourceManager.GetString("VerifyServersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Install Path.
        /// </summary>
        internal static string WelcomeInstallPathInvalid {
            get {
                return ResourceManager.GetString("WelcomeInstallPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trebuchet data path is not found. Please choose a new one..
        /// </summary>
        internal static string WelcomeInstallPathInvalidText {
            get {
                return ResourceManager.GetString("WelcomeInstallPathInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeSettingTutorial {
            get {
                return ResourceManager.GetString("WelcomeSettingTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Trebuchet.\n\nIn order to use the software for launching your game or servers you need to point the location of your game, or select how many server you wish the launcher to handle, or both.\n\nOther section of the launcher will unlock as you set those settings up..
        /// </summary>
        internal static string WelcomeSettingTutorialText {
            get {
                return ResourceManager.GetString("WelcomeSettingTutorialText", resourceCulture);
            }
        }
    }
}
